### ISSUE TITLE
custom loading indicator and button icon 

### ISSUE THREAD

**Issue by i-amin** [sachinchoolur/ladda-angular#1]
can we make the directives as containers and be able to insert a custom loading indicator and icons for the button

**Comment by rvanbaalen** [comment]
Or perhaps use a `provider` to configure such templates.

**Comment by sachinchoolur** [comment]
Hi,
You cannot use custom loading indicator but you can customize the behavior of spinner by adjusting `data-spinner-size` and `data-spinner-color`.
- data-spinner-size: 40, pixel dimensions of spinner, defaults to dynamic size based on the button height
- data-spinner-color: A hex code or any named CSS color. 

If you want to insert icons insert it inside `.ladda-label`
Please have a look at the demo http://codepen.io/anon/pen/GgBxaM

**Comment by rvanbaalen** [comment]
It's clear that we cannot do this -- this issue was meant as a feature
request (and should be labeled as such).

---

Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by i-amin** [comment]
@rvanbaalen .. exactly that's what i need to say
