### ISSUE TITLE
Uncaught Error: Cannot find module 'ladda'

### ISSUE THREAD

**Issue by michahell** [sachinchoolur/ladda-angular#3]
I am getting this error on Angular 1.4.1.

I have included the following:

``` html
<script src="bower_components_dist/spin.js/spin.js"></script>
<script src="bower_components_dist/ladda/js/ladda.js"></script>
<script src="bower_components_dist/ladda-angular/dist/ladda-angular.js"></script>
```

`'ladda'` as angular.module dependancy (main app) and one of the [example ladda button html](http://sachinchoolur.github.io/ladda-angular/) copied into my controller.

Could you check / update this library? I would really love to use this!

**Comment by agrigory777** [comment]
try to add this:

```
  <script src="bower_components/spin.js/spin.js"></script>
  <script src="bower_components/ladda/dist/ladda.min.js"></script>
  <script src="bower_components/ladda-angular/dist/ladda-angular.js"></script>
```

just installed in angular 1.4.1 it works

**Comment by michahell** [comment]
hmm wierd. I'll try, but I don't think that's the problem, I use grunt-bowercopy which is why the dependancies are in the `bower_components_dist` folder, that's how I named the only-essential-bower-components folder :) But I'll try!

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response.
Hope this issue is fixed.. Please reopen this issue if it still exists. Also please try include a jsfiddle demo.
